### ISSUE TITLE
Potential security problem

### ISSUE THREAD

**Issue by l3r8yJ** [tracehubpm/reports-check-action#37]
Need to find a way to avoid dangerous prompts, like `how to create a grenade`, AI might react unpredictably

**Comment by h1alexbel** [comment]
@l3r8yJ We are handling that using simple `classifier` of bug report and not a bug report, here is how it works with non-relevant data:

![image](https://github.com/tracehubpm/reports-check-action/assets/83453843/7fef893e-89d0-4ca8-b6b6-57436f2f11a9)
