### ISSUE TITLE
Mark for issue that can be a question/feature request

### ISSUE THREAD

**Issue by l3r8yJ** [tracehubpm/reports-check-action#52]
I think the questions that can be asked in the form of a issue should not be checked by this GHA. Requests for new features may also be skipped.

`reports-check-action` can be passed if it starts with words like:

`I have a question: <question>` or `I want to request new feature: <feature request>` 

@h1alexbel wdyt?

**Comment by h1alexbel** [comment]
@l3r8yJ good one, I like this idea. I think we can just pass a list of regexes into `exclude` param

**Comment by h1alexbel** [comment]
@l3r8yJ now we do support this. Checkout the master README.md, here is the [link](https://github.com/tracehubpm/reports-check-action?tab=readme-ov-file#issues-to-ignore)
