### ISSUE TITLE
list of suggestions is too long

### ISSUE THREAD

**Issue by yegor256** [tracehubpm/reports-check-action#64]
Take a look at this one: https://github.com/yegor256/qulice/issues/1242#issuecomment-2019426668

The list of suggestions is too long. Because of this, programmers simply ignore the entire message. Would be great to limit the list of suggestions to just three, to increase the probably of improvement.

**Comment by h1alexbel** [comment]
@yegor256 thanks for the report. Got it. I like the idea of limiting the number of "things to improve"

**Comment by h1alexbel** [comment]
@yegor256 now it should generate maximum 3 suggestions per issue/puzzle
