### ISSUE TITLE
print suggestions too

### ISSUE THREAD

**Issue by yegor256** [tracehubpm/reports-check-action#69]
Would be nice to get suggestions/corrections, not only criticism. Would be nice if the message would be: "the title of the issue is not good, this one would sound better: ..."

**Comment by h1alexbel** [comment]
@h1alexbel thanks for this issue. We are working on this as part of #66

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#73](https://github.com/tracehubpm/reports-check-action/issues/73) is still not solved.

**Comment by h1alexbel** [comment]
@yegor256 now this plugin is capable of generating suggestion too

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#73](https://github.com/tracehubpm/reports-check-action/issues/73) is solved here.
