### ISSUE TITLE
reports are too verbose

### ISSUE THREAD

**Issue by yegor256** [tracehubpm/reports-check-action#98]
Take a look at this one: https://github.com/objectionary/eo/issues/3127#issuecomment-2069314142

Such a long report is absolutely useless. Nobody reads it and nobody pays attention. In order to be useful, it has to be short and suggest **only one** specific improvement to be made. The message should be short (less than 30 words, I believe).

**Comment by h1alexbel** [comment]
@yegor256 thanks for reporting this problem. Agreed, our improvements suggestion system is not good as we want, our next step is to make one suggestion only.

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.3.3`

**Comment by h1alexbel** [comment]
@yegor256 we released a new version. Now it should look like this:

![image](https://github.com/tracehubpm/reports-check-action/assets/83453843/a9ff316b-2073-42f3-bf8d-58ab06a693e7)

**Comment by yegor256** [comment]
@h1alexbel I believe, the best format would be a strictly one-sentence message saying: "I would recommend ..."

**Comment by h1alexbel** [comment]
@yegor256 you mean drop problems and post **only one** suggestion?

**Comment by h1alexbel** [comment]
@yegor256 how about this?

![image](https://github.com/tracehubpm/reports-check-action/assets/83453843/b5fdecf7-bfdf-4570-b817-a74aff078a6b)

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.3.4`

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.3.5`

**Comment by h1alexbel** [comment]
@yegor256 now should be fixed!
